model:
  name: MCFlowDiTLarge
  image_size: 32
  in_channels: 4
  patch_size: 2

  hidden_size: 640
  num_heads: 10
  mlp_ratio: 3.0
  text_mlp_ratio: 1.0

  double_stream_blocks: 4
  single_stream_blocks: 8

  text_dim: 768
  max_text_tokens: 1

  qk_norm: true
  rope: 2d
  activation: swiglu
  bias: false

  cond_dropout: 0.12
